# Generated by Django 3.2.12 on 2022-03-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_submitwaste_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitwaste',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
