# Generated by Django 3.2.12 on 2022-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_submitwaste_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectwaste',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
