# Generated by Django 3.2.12 on 2022-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitwaste',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submitwaste',
            name='quantityofwaste',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
