# Generated by Django 3.2.12 on 2022-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_submitwaste_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitwaste',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
