# Generated by Django 3.2.12 on 2022-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_submitwaste_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectwaste',
            name='typerequired',
        ),
        migrations.AddField(
            model_name='collectwaste',
            name='communityName',
            field=models.CharField(choices=[('household', 'Household'), ('industry', 'Industry'), ('market', 'Market'), ('office', 'Office')], default='household', max_length=1024),
        ),
        migrations.AddField(
            model_name='collectwaste',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='collectwaste',
            name='fullname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='collectwaste',
            name='quantityofwaste',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='collectwaste',
            name='typeofwaste',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('glass', 'Glass'), ('organic', 'Organic')], default='organic', max_length=1024),
        ),
        migrations.AddField(
            model_name='collectwaste',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collectwaste',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
